### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by mastak**
Hi @altaurog.
Thank you for you lib, it was very useful!

Also in my case, I need extra formatters, that did not exist, so I added them and added Docker environment for running tests local without any requirements, except Docker.

### CODE REVIEW

**Comment by altaurog** [comment]
Thanks, @mastak, for your efforts!  I am glad you find the lib useful, and really appreciate your contribution.  I see you cleaned up the existing code too, which is great.  I'd love to merge these awesome improvements.  Could you please split it into separate commits?  It looks like there should be one for removing unused import, one for whitespace changes, one for refactoring the error handling, and one for the new types.  Just a personal commit style thing.  Thanks.

**Comment by mastak** [comment]
It seems Travis uses old Postgres, which doesn't support  JSON and JSONB fields. Can you set up Travis to use Postgres 9.3 or newer?

**Comment by altaurog** [comment]
Yes, I'll have a look.  It would be nice if we could skip the json tests if postgresql version doesn't support them, though.

**Comment by altaurog** [comment]
@mastak you can set postgresql version in .travis.yml:
https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version

**Comment by altaurog** [comment]
I fixed the tests and merged most of the changes.  I don't think there's much use case for overriding formatters, but adding new ones could be useful.  I would prefer a slightly different approach; will look at that soon, time permitting.  I also added you as a contributor in a new AUTHORS file.

**Pull request closed without merging**
