### PR TITLE
Fix quickstart example.

### PR DESCRIPTION
**Pull request by nikitagruia-dev**

### CODE REVIEW

**Comment by altaurog** [comment]
I am afraid I don’t understand.  What is this for?

**Comment by gruianichita** [comment]
> I am afraid I don’t understand. What is this for?

It's just because columns in CopyManager annotated as a list of strings :D Not so important, but code looks good without IDE warnings

**Comment by altaurog** [comment]
> It's just because columns in CopyManager annotated as a list of strings

Where?  Do you mean in the docstring?

**Comment by gruianichita** [comment]
> Where? Do you mean in the docstring?
yep

**Comment by altaurog** [comment]
Interesting.  What IDE are you using?  I didn’t know they read those.  If you instead change the docstring to iterable of str, would that work?

**Comment by gruianichita** [comment]
I'm using PyCharm.Yes, pycharm read that types, can u define as iterable in docstring?

**Pull request closed without merging**
